drop table categoriasproductos;


CREATE TABLE CategoriasProductos (
    CategoriaID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NombreCategoria VARCHAR(50)
);

INSERT INTO CategoriasProductos (NombreCategoria) VALUES ('Electrónica');
INSERT INTO CategoriasProductos (NombreCategoria) VALUES ('Ropa');
INSERT INTO CategoriasProductos (NombreCategoria) VALUES ('Hogar');
INSERT INTO CategoriasProductos (NombreCategoria) VALUES ('Alimentos');
INSERT INTO CategoriasProductos (NombreCategoria) VALUES ('Juguetes');

select * from CategoriasProductos;

ALTER TABLE CategoriasProductos
  ADD (
    CONSTRAINT CTPK PRIMARY KEY (CategoriaID)
  );


CREATE TABLE Productos (
    ProductoID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NombreProducto VARCHAR(50),
    Precio REAL,
    CategoriaID INTEGER,
    FOREIGN KEY (CategoriaID) REFERENCES CategoriasProductos(CategoriaID)
);

INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Televisor LCD 40 pulgadas', 559292, 1);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Camiseta de algodón', 15989, 2);       
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Sofá seccional', 719191, 3);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Arroz integral', 3993, 4);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Muñeca Barbie', 23992, 5);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Laptop Dell', 719191, 1);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Pantalones vaqueros', 31992, 2);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Mesa de comedor', 239992, 3);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Leche desnatada', 1992, 4);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Carro de control remoto', 19992, 5);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Smartphone Samsung', 559292, 1);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Blusa de seda', 39992, 2);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Cama king size', 479992, 3);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Manzanas', 791, 4);
INSERT INTO Productos (NombreProducto, Precio, CategoriaID) VALUES('Robot educativo', 27992, 5);

DROP TABLE Clientes;
CREATE TABLE Clientes (
    ClienteID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      NombreCliente VARCHAR2(100)
);
INSERT INTO Clientes (NombreCliente) VALUES('Luis');
INSERT INTO Clientes (NombreCliente) VALUES('Ana');
INSERT INTO Clientes (NombreCliente) VALUES('Pedro');
INSERT INTO Clientes (NombreCliente) VALUES('María');
INSERT INTO Clientes (NombreCliente) VALUES('Telefónica S.A');
INSERT INTO Clientes (NombreCliente) VALUES('Cementos Inc.');
INSERT INTO Clientes (NombreCliente) VALUES('Carlos');
INSERT INTO Clientes (NombreCliente) VALUES('Laura');
INSERT INTO Clientes (NombreCliente) VALUES('Banco ABC');
INSERT INTO Clientes (NombreCliente) VALUES('Energía SA');
INSERT INTO Clientes (NombreCliente) VALUES('Juan');
INSERT INTO Clientes (NombreCliente) VALUES('Isabel');
INSERT INTO Clientes (NombreCliente) VALUES('Constructora XYZ');
INSERT INTO Clientes (NombreCliente) VALUES('Automóviles MNO');
INSERT INTO Clientes (NombreCliente) VALUES('Sofía');


CREATE TABLE Empleados (
    EmpleadoID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NombreEmpleado VARCHAR2(150),
    SueldoBruto REAL
);


INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Carlos', 398500);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Ana', 521000);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Pedro', 450200);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Sofía', 563700);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Luis', 375800);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('María', 492300);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Javier', 408600);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Laura', 575900);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Isabel', 359400);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Juan', 597100);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Andrés', 476800);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Valentina', 582500);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Miguel', 364700);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Alejandra', 415600);
INSERT INTO Empleados (NombreEmpleado, SueldoBruto) VALUES('Ricardo', 523900);

CREATE TABLE OrdenesTrabajo (
    OrdenID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FechaOrden DATE,
    ClienteID INTEGER,
    EmpleadoID INTEGER,
    Estado VARCHAR2(100),
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
    FOREIGN KEY (EmpleadoID) REFERENCES Empleados(EmpleadoID)
);

INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023/03/01','YYYY-MM-DD'), 11, 7, 'Completada');

INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-02','YYYY-MM-DD'), 12, 3, 'Pendiente');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-03','YYYY-MM-DD'), 13, 8, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-04','YYYY-MM-DD'), 14, 1, 'Cancelada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-05','YYYY-MM-DD'), 15, 9, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-06','YYYY-MM-DD'), 11, 12, 'Pendiente');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-07','YYYY-MM-DD'), 12, 14, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-08','YYYY-MM-DD'), 13, 6, 'Cancelada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-09','YYYY-MM-DD'), 14, 5, 'Pendiente');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-10','YYYY-MM-DD'), 15, 2, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-11','YYYY-MM-DD'), 11, 11, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-12','YYYY-MM-DD'), 12, 13, 'Cancelada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-13','YYYY-MM-DD'), 13, 15, 'Pendiente');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-14','YYYY-MM-DD'), 14, 10, 'Completada');
INSERT INTO OrdenesTrabajo (FechaOrden, ClienteID, EmpleadoID, Estado) VALUES(TO_DATE('2023-03-15','YYYY-MM-DD'), 15, 4, 'Completada');